"""sprint6 chat message tombstone fields

Revision ID: 2a0a036535f9
Revises: 53a611bb60bc
Create Date: 2026-08-18 06:00:56.079995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2a0a036535f9'
down_revision: Union[str, None] = '53a611bb60bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('deleted_by_id', sa.UUID(), nullable=True))
    op.add_column('chat_messages', sa.Column('deleted_reason', sa.String(length=300), nullable=True))
    op.create_foreign_key(
        'fk_chat_messages_deleted_by_id_users',
        'chat_messages',
        'users',
        ['deleted_by_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_chat_messages_deleted_by_id_users', 'chat_messages', type_='foreignkey')
    op.drop_column('chat_messages', 'deleted_reason')
    op.drop_column('chat_messages', 'deleted_by_id')
    # ### end Alembic commands ###
