import 'package:campusconnect/design_system/material.dart';

/// Atlas Dark palette (whole.md §3.1) — pasted verbatim. These hexes are the
/// design. Never derive schemes with `ColorScheme.fromSeed` (Law 2): seeded
/// neutrals come out hue-tinted and muddy.
abstract final class AppColors {
  static const dark = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFF818CF8),
    onPrimary: Color(0xFF1A1150),
    primaryContainer: Color(0xFF2E2A6B),
    onPrimaryContainer: Color(0xFFDDE0FF),
    secondary: Color(0xFFA5A8B8),
    onSecondary: Color(0xFF12131A),
    secondaryContainer: Color(0xFF212228),
    onSecondaryContainer: Color(0xFFE6E7EC),
    tertiary: Color(0xFF3DD9A0),
    onTertiary: Color(0xFF00382A),
    tertiaryContainer: Color(0xFF00513C),
    onTertiaryContainer: Color(0xFFB7F2D8),
    error: Color(0xFFFF6B6B),
    onError: Color(0xFF3A0A0A),
    errorContainer: Color(0xFF6E1F1F),
    onErrorContainer: Color(0xFFFFDAD6),
    surface: Color(0xFF0A0A0C),
    onSurface: Color(0xFFF4F4F5),
    onSurfaceVariant: Color(0xFFA1A1AA),
    surfaceContainerLowest: Color(0xFF060608),
    surfaceContainerLow: Color(0xFF131316),
    surfaceContainer: Color(0xFF18181C),
    surfaceContainerHigh: Color(0xFF1F1F24),
    surfaceContainerHighest: Color(0xFF26262C),
    surfaceDim: Color(0xFF0A0A0C),
    surfaceBright: Color(0xFF2E2E35),
    outline: Color(0xFF3F3F49),
    outlineVariant: Color(0xFF2A2A31),
    inverseSurface: Color(0xFFF4F4F5),
    onInverseSurface: Color(0xFF18181C),
    inversePrimary: Color(0xFF4F46E5),
    shadow: Color(0xFF000000),
    scrim: Color(0xFF000000),
    surfaceTint: Colors.transparent,
  );

  static const light = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF4F46E5),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFE0E1FF),
    onPrimaryContainer: Color(0xFF14116B),
    secondary: Color(0xFF52525B),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFEFF0F3),
    onSecondaryContainer: Color(0xFF1A1C20),
    tertiary: Color(0xFF12805C),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFB7F2D8),
    onTertiaryContainer: Color(0xFF00281C),
    error: Color(0xFFB3261E),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFF9DEDC),
    onErrorContainer: Color(0xFF410E0B),
    surface: Color(0xFFFFFFFF),
    onSurface: Color(0xFF0E0E11),
    onSurfaceVariant: Color(0xFF63636E),
    surfaceContainerLowest: Color(0xFFFFFFFF),
    surfaceContainerLow: Color(0xFFFAFAFB),
    surfaceContainer: Color(0xFFF4F4F6),
    surfaceContainerHigh: Color(0xFFEDEDF0),
    surfaceContainerHighest: Color(0xFFE4E4E8),
    surfaceDim: Color(0xFFE8E8EC),
    surfaceBright: Color(0xFFFFFFFF),
    outline: Color(0xFFC9C9D1),
    outlineVariant: Color(0xFFE6E6EA),
    inverseSurface: Color(0xFF18181C),
    onInverseSurface: Color(0xFFF4F4F5),
    inversePrimary: Color(0xFFB4B8FF),
    shadow: Color(0xFF000000),
    scrim: Color(0xFF000000),
    surfaceTint: Colors.transparent,
  );
}
